const resArrList = [
  {
    info: {
      id: "786467",
      name: "Paratha Wala",
      cloudinaryImageId: "af8349c33cc194911e3870097f79b0d5",
      locality: "Mahesh Nagar",
      areaName: "Srikrishnapuri",
      costForTwo: "₹200 for two",
      cuisines: ["Thalis", "Chinese"],
      avgRating: 3.3,
      veg: true,
      parentId: "13893",
      avgRatingString: "3.3",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 76,
        lastMileTravel: 6.7,
        serviceability: "SERVICEABLE",
        slaString: "75-80 mins",
        lastMileTravelString: "6.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 10:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/paratha-wala-mahesh-nagar-srikrishnapuri-patna-786467",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "352207",
      name: "Hotel Sidh Vedantha",
      cloudinaryImageId: "ecnxjlvnx5tppareepbw",
      locality: "Kankarbagh",
      areaName: "Lohia Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Biryani", "Indian"],
      avgRating: 4.2,
      parentId: "437308",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 61,
        lastMileTravel: 1.8,
        serviceability: "SERVICEABLE",
        slaString: "60-65 mins",
        lastMileTravelString: "1.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 23:55:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-sidh-vedantha-kankarbagh-lohia-nagar-patna-352207",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "815738",
      name: "Cake Master",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/8/eee6b62c-bd18-464c-80ae-8ab0f15ce69e_815738.jpg",
      locality: "Kankarbagh",
      areaName: "Kankarbagh",
      costForTwo: "₹200 for two",
      cuisines: ["Indian"],
      avgRating: 3.2,
      parentId: "12617",
      avgRatingString: "3.2",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 64,
        lastMileTravel: 2.8,
        serviceability: "SERVICEABLE",
        slaString: "60-65 mins",
        lastMileTravelString: "2.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/cake-master-kankarbagh-patna-815738",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "863062",
      name: "Pizza Hub",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/3/29/74ca6e7f-b96f-4950-ad33-05a257242142_863062.jpg",
      locality: "Srikrishnapuri",
      areaName: "Srikrishnapuri",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas", "Fast Food", "Burgers"],
      avgRating: 4.7,
      parentId: "14585",
      avgRatingString: "4.7",
      totalRatingsString: "7",
      sla: {
        deliveryTime: 68,
        lastMileTravel: 5.7,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "5.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 09:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹599",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/pizza-hub-srikrishnapuri-patna-863062",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "810602",
      name: "Annapurna Rasoi",
      cloudinaryImageId: "a6191b983b6f25f9dc82780a244ed21e",
      locality: "Agam Kuan Shitala Colony",
      areaName: "Kankarbagh",
      costForTwo: "₹299 for two",
      cuisines: [
        "Chinese",
        "Mughlai",
        "Indian",
        "Asian",
        "Tandoor",
        "Bihari",
        "Home Food",
        "Fast Food",
      ],
      avgRating: 4.2,
      parentId: "34128",
      avgRatingString: "4.2",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 86,
        lastMileTravel: 7.8,
        serviceability: "SERVICEABLE",
        slaString: "85-90 mins",
        lastMileTravelString: "7.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 23:59:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "UPTO ₹45",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/annapurna-rasoi-agam-kuan-shitala-colony-kankarbagh-patna-810602",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "870513",
      name: "Pizza King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/14/9d4c93c1-9eef-492d-91a6-ad2a6c03bbc1_870513.jpg",
      locality: "Srikrishnapuri",
      areaName: "Srikrishnapuri",
      costForTwo: "₹300 for two",
      cuisines: ["Beverages", "Pizzas"],
      avgRating: 5,
      veg: true,
      parentId: "4202",
      avgRatingString: "5.0",
      totalRatingsString: "2",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 5.7,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "5.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 09:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/pizza-king-srikrishnapuri-patna-870513",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "343468",
      name: "Cake 24x7",
      cloudinaryImageId: "yuai9tmymsdhq4az9os2",
      locality: "Road No 12",
      areaName: "Don Bosco Raod",
      costForTwo: "₹400 for two",
      cuisines: ["Bakery", "Indian", "Ice Cream Cakes", "Cakes and Pastries"],
      avgRating: 3.8,
      veg: true,
      parentId: "54688",
      avgRatingString: "3.8",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 53,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "50-55 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-18 00:00:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/cake-24x7-road-no-12-don-bosco-raod-patna-343468",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "815741",
      name: "Cake Point",
      cloudinaryImageId: "e1114ef2ed8df79fdf4acaee0ec0b040",
      locality: "Kankarbagh",
      areaName: "Kankarbagh",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery"],
      parentId: "2650",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 57,
        lastMileTravel: 2.8,
        serviceability: "SERVICEABLE",
        slaString: "55-60 mins",
        lastMileTravelString: "2.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-11 23:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/cake-point-kankarbagh-patna-815741",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "402137",
      name: "Veg Food Hub",
      cloudinaryImageId: "pa2xtea4hyzd47o37jy5",
      locality: "Machua Toli",
      areaName: "Bakerganj",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Fast Food", "Italian"],
      avgRating: 3.8,
      veg: true,
      parentId: "222100",
      avgRatingString: "3.8",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 4.4,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "4.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 00:15:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-bb81fa5b-7349-4c02-b12f-a22965db7a99",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/veg-food-hub-machua-toli-bakerganj-patna-402137",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },

  {
    info: {
      id: "402138",
      name: "Veg Food Hub",
      cloudinaryImageId: "pa2xtea4hyzd47o37jy5",
      locality: "Machua Toli",
      areaName: "Bakerganj",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Fast Food", "Italian"],
      avgRating: 3.8,
      veg: true,
      parentId: "222100",
      avgRatingString: "3.8",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 4.5,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "4.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "402139",
      name: "Veg Food Hub",
      cloudinaryImageId: "pa2xtea4hyzd47o37jy5",
      locality: "Machua Toli",
      areaName: "Bakerganj",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Fast Food", "Italian"],
      avgRating: 3.8,
      veg: true,
      parentId: "222100",
      avgRatingString: "3.8",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 2.5,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "4.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },

  {
    info: {
      id: "402140",
      name: "Veg Food Hub",
      cloudinaryImageId: "pa2xtea4hyzd47o37jy5",
      locality: "Machua Toli",
      areaName: "Bakerganj",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Fast Food", "Italian"],
      avgRating: 3.8,
      veg: true,
      parentId: "222100",
      avgRatingString: "4.8",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 4.5,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "4.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
];

export default resArrList;
